// URL ↔ 日本語ページ名の一元管理
// Next.jsのmetadata、analytics、その他で共通利用
export const PAGE_TITLES: Record<string, string> = {
  "/":                         "蛟龍祭 場内サイト",
  "/enter":                    "QR表示",
  "/vote":                     "クラス投票",
  "/vote/confirm":             "投票確認",
  "/event-enter":              "イベント入場・投票",
  "/puzzle":                   "謎解き",
  "/map":                      "マップ",
  "/info":                     "インフォメーション",
  "/history":                  "履歴",
  "/penlight":                 "ペンライト",
  "/survey":                   "アンケート",
  "/register":                 "入場登録",
  "/admin":                    "管理者メニュー",
  "/admin/login":              "管理者ログイン",
  "/admin/classes":            "クラス管理",
  "/admin/map":                "混雑マップ設定",
  "/admin/info":               "インフォメーション管理",
  "/admin/vote-results":       "クラス投票得票数",
  "/admin/analytics":          "アクセス解析",
  "/admin/pin-content":        "ピン情報管理",
  "/admin/festival-settings":  "日程・表示設定",
  "/admin/puzzle-redeem":      "景品引換スキャン",
  "/admin/venue/gym":          "体育館管理",
  "/admin/venue/gym/nodojiman":          "のど自慢",
  "/admin/venue/gym/coscon_performance": "コスコン（パフォーマンス）",
  "/admin/venue/gym/coscon_runway":      "コスコン（ランウェイ）",
  "/admin/venue/kinenkan":     "記念館管理",
  "/admin/venue/koryokan":     "ライブ管理",
  "/admin/venue/library":      "図書館管理",
  "/admin/venue/shogi":        "将棋部管理",
  "/admin/venue/igo":          "囲碁部管理",
  "/admin/venue/science":      "科学物理部管理",
  "/admin/venue/tetsudo":      "鉄道研究部管理",
  "/admin/venue/quiz":         "クイズ研究会管理",
  "/admin/venue/bazar":        "バザー管理",
  "/admin/venue/doso":         "同窓会管理",
  "/admin/venue/kyukei":       "休憩所管理",
  "/admin/venue/kendo":        "剣道部管理",
  "/admin/venue/kyudo":        "弓道部管理",
  "/event-admin":              "イベント管理",
  "/event-manage":             "イベント投票管理",
  "/staff":                    "係員スキャン",
  "/staff/settings":           "係員設定",
};

export function getPageTitle(path: string): string {
  return PAGE_TITLES[path] ?? "蛟龍祭 場内システム";
}
